# Generated by Django 5.1 on 2024-12-03 09:26

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_title_alter_product_mark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, default=product.models.get_default_product_image, null=True, upload_to=product.models.get_product_image_filepath),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, default=product.models.get_default_product_image, null=True, upload_to=product.models.get_product_image_filepath),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, default=product.models.get_default_product_image, null=True, upload_to=product.models.get_product_image_filepath),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, default=product.models.get_default_product_image, null=True, upload_to=product.models.get_product_image_filepath),
        ),
    ]
